#!/bin/bash
# Usage: ./switch-env.sh [devLocal|devDocker|serverDocker]
# Configure once in .env:
#   SERVER_DOCKER_BACKEND_IP=172.16.60.186
# Optional one-off override:
#   BACKEND_IP=172.16.60.186 ./switch-env.sh serverDocker
#
# Modes:
#   devLocal      -> frontend runs NATIVELY (astro dev); backend on localhost:3000.
#                    .env patched only; docker compose is NOT touched.
#   devDocker     -> frontend container on the SAME Docker host as the backend
#                    container; joined to the backend's Compose network.
#   serverDocker  -> production: frontend container on dittfront; backend reached
#                    over OpenStack private network at SERVER_DOCKER_BACKEND_IP.
#
# PUBLIC_* / SERVER_* values are baked into the JS bundle at build time via
# Docker build args, so every mode change for devDocker/serverDocker rebuilds
# with --no-cache.

set -e
MODE=$1

case "$MODE" in
  devLocal|devDocker|serverDocker) ;;
  *)
    echo "Usage: $0 [devLocal|devDocker|serverDocker]"
    echo "  devLocal      - native astro dev, backend on localhost"
    echo "  devDocker     - frontend container; backend container on same host"
    echo "  serverDocker  - frontend container; backend from .env SERVER_DOCKER_BACKEND_IP"
    echo ""
    echo "  Configure once: SERVER_DOCKER_BACKEND_IP=<ip> in .env"
    echo "  Optional override: BACKEND_IP=<ip> ./switch-env.sh serverDocker"
    exit 1
    ;;
esac

if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
    echo "Bootstrapped .env from .env.example (fill in secrets before using)."
  else
    echo "Error: .env not found in $(pwd) and no .env.example available."
    exit 1
  fi
fi

# Read KEY=value from .env (last occurrence wins).
read_env_value() {
  local key="$1"
  local raw
  raw="$(grep -E "^${key}=" .env | tail -n 1 | cut -d'=' -f2- | tr -d '\r')"
  raw="$(printf '%s' "$raw" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  raw="${raw#\"}"
  raw="${raw%\"}"
  printf '%s' "$raw"
}

CONFIG_SERVER_BACKEND_IP="$(read_env_value SERVER_DOCKER_BACKEND_IP)"
BACKEND_IP="${BACKEND_IP:-${CONFIG_SERVER_BACKEND_IP:-172.16.60.186}}"

echo "Switching frontend to '$MODE' mode (BACKEND_IP=$BACKEND_IP)..."

upsert() {
  local key="$1" value="$2"
  if grep -qE "^${key}=" .env; then
    sed -i.bak "s|^${key}=.*|${key}=${value}|" .env
    rm -f .env.bak
  else
    printf '%s=%s\n' "$key" "$value" >> .env
  fi
}

# ---------------------------------------------------------------------------
# 1. Patch .env
# ---------------------------------------------------------------------------
case "$MODE" in
  devLocal)
    upsert NODE_ENV             'development'
    upsert PUBLIC_IS_DEV        'true'
    upsert PUBLIC_API_BASE_URL  'https://localhost:3000/api'
    upsert SERVER_API_BASE_URL  'https://localhost:3000/api'
    ;;
  devDocker)
    upsert NODE_ENV             'development'
    upsert PUBLIC_IS_DEV        'true'
    upsert PUBLIC_API_BASE_URL  'https://localhost:3000/api'
    upsert SERVER_API_BASE_URL  'https://backend:3000/api'
    ;;
  serverDocker)
    upsert NODE_ENV             'production'
    upsert PUBLIC_IS_DEV        'false'
    upsert PUBLIC_API_BASE_URL  'https://localhost:3000/api'
    upsert SERVER_API_BASE_URL  "https://${BACKEND_IP}:3000/api"
    ;;
esac

echo ".env patched for '$MODE' mode."

# ---------------------------------------------------------------------------
# 2. docker-compose.yml + container lifecycle
# ---------------------------------------------------------------------------
if [[ "$MODE" == "devLocal" ]]; then
  echo "devLocal: skipping docker compose (run 'pnpm dev' natively)."
  exit 0
fi

if [[ "$MODE" == "devDocker" ]]; then
  cat > docker-compose.yml <<'EOF'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_API_BASE_URL: https://localhost:3000/api
        SERVER_API_BASE_URL: https://backend:3000/api
        PUBLIC_IS_DEV: "true"
    restart: unless-stopped
    environment:
      PUBLIC_API_BASE_URL: https://localhost:3000/api
      SERVER_API_BASE_URL: https://backend:3000/api
      PUBLIC_IS_DEV: true
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      HOST: 0.0.0.0
      PORT: 4321
      HTTPS_KEY_PATH: /app/certs/server.key
      HTTPS_CERT_PATH: /app/certs/server.crt
      HTTPS_CA_PATH: /app/certs/ca.crt
    volumes:
      - ../TC3005B.501-Backend/certs:/app/certs:ro
    networks:
      - default
      - backend_net
    ports:
      - "4321:4321"

networks:
  backend_net:
    external: true
    name: tc3005b501-backend_default
EOF
fi

if [[ "$MODE" == "serverDocker" ]]; then
  cat > docker-compose.yml <<EOF
# Generated by switch-env.sh (serverDocker mode).
# Backend is expected at https://${BACKEND_IP}:3000 (OpenStack private network).
# Configure once in .env: SERVER_DOCKER_BACKEND_IP=<real_ip>
# Optional one-off: BACKEND_IP=<real_ip> ./switch-env.sh serverDocker
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_API_BASE_URL: https://localhost:3000/api
        SERVER_API_BASE_URL: https://${BACKEND_IP}:3000/api
        PUBLIC_IS_DEV: "false"
    restart: unless-stopped
    environment:
      PUBLIC_API_BASE_URL: https://localhost:3000/api
      SERVER_API_BASE_URL: https://${BACKEND_IP}:3000/api
      PUBLIC_IS_DEV: false
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      HOST: 0.0.0.0
      PORT: 4321
      HTTPS_KEY_PATH: /app/certs/server.key
      HTTPS_CERT_PATH: /app/certs/server.crt
      HTTPS_CA_PATH: /app/certs/ca.crt
    volumes:
      - /home/dittravel/certs:/app/certs:ro
    ports:
      - "4321:4321"
EOF
fi

echo "docker-compose.yml rewritten for '$MODE' mode."

# Build args are baked at build time -> --no-cache is mandatory.
# By default, avoid full shutdown to reduce unnecessary restarts.
# Use FORCE_DOWN=1 (or true) when you explicitly want a full stop/start cycle.
if [[ "${FORCE_DOWN:-0}" == "1" || "${FORCE_DOWN:-false}" == "true" ]]; then
  echo "FORCE_DOWN enabled -> running docker compose down"
  docker compose down
fi

docker compose build --no-cache
docker compose up -d --remove-orphans

echo "Done. Frontend running in '$MODE' mode."
docker compose ps
