# ------------------------------------------------------------------
# Sub-Task Issue Template
# Use this template for highly specific, focused units of work that
# contribute toward completing a larger Task.
#
# Sub-Tasks should:
# - Be small and independently completable
# - Be assignable to a single individual where possible
# - Have clearly defined scope and outcome
# - Roll up into a parent Task
#
# This template automatically:
# - Prefixes the issue title with [Sub-Task]
# - Adds the issue to the dittravel project board
# ------------------------------------------------------------------

name: Sub-Task
description: A highly specific piece of work that builds towards a task, and that requires to be tracked, discussed, and worked on independently. Probably by a single individual.
title: "[Sub-Task]: "
type: 2-Sub-Task
projects: dittravel
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear explanation of what this specific sub-task needs to accomplish.
      placeholder: Describe the exact functionality or component to be implemented in this sub-task.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Specific technical details and requirements for this sub-task.
      placeholder: |
        - Specific component or feature to implement
        - Data structures or APIs involved
        - UI/UX requirements
        - Edge cases to handle
    validations:
      required: true
  - type: textarea
    id: checklist
    attributes:
      label: Checklist to complete issue
      description: Detailed steps to complete this sub-task.
      placeholder: |
        - Step 1: Implement core functionality
        - Step 2: Add error handling
        - Step 3: Write unit tests
        - Step 4: Update documentation
